import Title from "components/Title/Title";
import useMediaQuery from "hooks/useMediaQuery";
import Navbar from "layouts/Navbar/Navbar";
import React from "react";
import styles from "./TermsAndConditions.module.css";

function TermsAndConditions() {
  const isBellow1000px = useMediaQuery("(max-width : 1000px)");
  const isBellow600px = useMediaQuery("(max-width : 600px)");

  return (
    <div>
      <div className={``}>
        <Navbar />
      </div>

      <div className="container-wrapper py-50px">
        <div className={isBellow600px ? "mb-40px" : "mb-60px"}>
          <Title
            title="TERMS And CONDITIONS"
            className={`${isBellow1000px ? "mb-20px" : "mb-40px"}`}
          />

          <p
            className={`${
              isBellow1000px
                ? isBellow600px
                  ? "fs-12px"
                  : "fs-16px"
                : "fs-22px"
            } opacity-0_8 white lh-1_6 mb-30px`}
          >
            Lucky Buddha Club is a collection of digital artworks (NFTs) running
            on the Ethereum network. This website is only an interface allowing
            participants to exchange digital collectibles. Users are entirely
            responsible for the safety and management of their own private
            Ethereum wallets and validating all transactions and contracts
            generated by this website before approval. Furthermore, as the Lucky
            Buddha Club smart contract runs on the Ethereum network, there is no
            ability to undo, reverse, or restore any transactions
          </p>
          <p
            className={`${
              isBellow1000px
                ? isBellow600px
                  ? "fs-12px"
                  : "fs-16px"
                : "fs-22px"
            } opacity-0_8 white lh-1_6`}
          >
            This website and its connected services are provided “as is” and “as
            available” without warranty of any kind. By using this website you
            are accepting sole responsibility for any and all transactions
            involving Lucky Buddha Club digital collectibles.
          </p>
        </div>
        <div className={isBellow600px ? "mb-40px" : "mb-60px"}>
          <Title
            title="OWNERSHIP AND BENEFITS"
            className={`${isBellow1000px ? "mb-30px" : "mb-40px"}`}
          />

          <p
            className={`${
              isBellow1000px
                ? isBellow600px
                  ? "fs-12px"
                  : "fs-16px"
                : "fs-22px"
            } opacity-0_8 white lh-1_6 mb-30px`}
          >
            i. You Own the NFT. Each Lucky Buddha is an NFT on the Ethereum
            blockchain. When you purchase an NFT, you own the underlying Lucky
            Buddha, the Art, completely. Ownership of the NFT is mediated
            entirely by the Smart Contract and the Ethereum Network: at no point
            may we seize, freeze, or otherwise modify the ownership of any Lucky
            Buddha
          </p>
          <p
            className={`${
              isBellow1000px
                ? isBellow600px
                  ? "fs-12px"
                  : "fs-16px"
                : "fs-22px"
            } opacity-0_8 white lh-1_6 mb-30px`}
          >
            ii. Any Rewards, gifts, giveaways, or participation of earnings of
            any kind are subject to circumstances in which Lucky Buddha Club is
            considered to be in a position that is financially viable to provide
            these benefits on an ongoing basis as described. It is Lucky Buddha
            Clubs priority and intention to provide all the benefits described
            and offered, so long as conditions are met benefits will be executed
            at the discretion of Lucky Buddha Club. Benefits will generally be
            paid through smart contracts, air drops, or any other methods Lucky
            Buddha club deems to be valid for payment or compensation.
          </p>
          <p
            className={`${
              isBellow1000px
                ? isBellow600px
                  ? "fs-12px"
                  : "fs-16px"
                : "fs-22px"
            } opacity-0_8 white lh-1_6 mb-30px`}
          >
            iii. Personal Use. Subject to your continued compliance with these
            Terms, you are granted a worldwide, license to use, copy, and
            display the purchased Art, along with any extensions that you choose
            to create or use, solely for the following purposes: (i) for your
            own personal, non-commercial use; (ii) as part of a marketplace that
            permits the purchase and sale of your Lucky Buddha / NFT, provided
            that the marketplace cryptographically verifies each Lucky Buddha
            owner’s rights to display the Art for their Lucky Buddha to ensure
            that only the actual owner can display the Art; or (iii) as part of
            a third party website or application that permits the inclusion,
            involvement, or participation of your Lucky Buddha,
          </p>
          <p
            className={`${
              isBellow1000px
                ? isBellow600px
                  ? "fs-12px"
                  : "fs-16px"
                : "fs-22px"
            } opacity-0_8 white lh-1_6 mb-30px`}
          >
            provided that the website/application cryptographically verifies
            each Lucky Buddha owner’s rights to display the Art for their Lucky
            Buddha to ensure that only the actual owner can display the Art, and
            provided that the Art is no longer visible once the owner of the
            Lucky Buddha leaves the website/application.
          </p>
        </div>
      </div>
    </div>
  );
}

export default TermsAndConditions;
